name: Update File on Feature Branch

on:
  push:
    branches:
      - main  # Trigger workflow when there's a push to the `main` branch

  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Git user
    - name: Set up Git user
      run: |
        git config --global user.name "Pavithran1508"
        git config --global user.email "pavithrang4@gmail.com"

    # Create or update the file
    - name: Create or Update a File
      run: |
        FILE_PATH="example-file.txt"  # Set the path to the file you want to modify
        echo "This is an updated line of content added on $(date)." >> $FILE_PATH  # Append a new line with the current date
        git add $FILE_PATH

    # Commit the changes
    - name: Commit changes
      run: |
        git commit -m "Update example-file.txt with new content" || echo "No changes to commit"

    # Push changes to feature branch
    - name: Push changes to feature branch
      run: |
        FEATURE_BRANCH="feature"
        git fetch origin $FEATURE_BRANCH || echo "Branch does not exist. Creating it."
        git checkout -b $FEATURE_BRANCH || git checkout $FEATURE_BRANCH
        git push origin HEAD:$FEATURE_BRANCH
