name: Update File in Feature Branch

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Git
      - name: Set up Git
        run: |
          git config user.name "Pavithran1508"
          git config user.email "pavithrang4@gmail.com"

      # Create or switch to the feature branch
      - name: Switch to feature branch
        run: |
          git fetch origin
          git checkout -B feature

      # Create or update the file
      - name: Create/Update file
        run: |
          echo "File updated on $(date)" > my-file.txt

      # Add and commit the file
      - name: Commit changes
        run: |
          git add my-file.txt
          git commit -m "Update my-file.txt" || echo "No changes to commit"

      # Push changes to the feature branch
      - name: Push changes
        run: |
          git push origin feature
